services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: moradelacms
      POSTGRES_DB: vehicle_cms
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'cms_user']
      interval: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      # no image: builder aquí
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - '3000:3000'

volumes:
  db_data:
